### ISSUE TITLE
TAKE PICTURE crashes if the Camera permission is off

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/KnightWatch#3]
### Problem Description:
In Android <= 5 if you request a permission in the manifest file, you have it forever. Remember that in Android 6+, users can turn off certain permissions through the system settings. I'm on Android 6 and have my security settings on lock-down, so the first time I tried the <kbd>TAKE PICTURE</kbd> button, the app crashed. Not good.

### Solution:
When the <kbd>TAKE PICTURE</kbd> button is pressed, we should check that we still have the `android.permission.CAMERA` permission, if not, we should display a popup, rather than calling the camera intent, saying something like "Cannot launch Camera. Please go into Settings > Apps > MCMergeManager > Permissions and enable Camera".

### Stack Trace from the crash:

    12-12 20:38:19.183 14078-14195/com.loyola.robotics.knightwatch E/AndroidRuntime: FATAL EXCEPTION: Timer-0
                                                                                 Process: com.loyola.robotics.knightwatch, PID: 14078
                                                                                 java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.google.android.GoogleCamera/com.android.camera.CaptureActivity clip={text/uri-list U:file:///storage/emulated/0/Pictures/Robotics%20Team%20Pics/3710.jpg} (has extras) } from ProcessRecord{27ab70a 14078:com.loyola.robotics.knightwatch/u0a136} (pid=14078, uid=10136) with revoked permission android.permission.CAMERA
                                                                                     at android.os.Parcel.readException(Parcel.java:1599)
                                                                                     at android.os.Parcel.readException(Parcel.java:1552)
                                                                                     at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2658)
                                                                                     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1507)
                                                                                     at android.app.Activity.startActivityForResult(Activity.java:3917)
                                                                                     at android.app.Activity.startActivityForResult(Activity.java:3877)
                                                                                     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:784)
                                                                                     at com.loyola.robotics.knightwatch.TakePicture.capturePicture(TakePicture.java:37)
                                                                                     at com.loyola.robotics.knightwatch.MainActivity$CheckVar.run(MainActivity.java:670)
                                                                                     at java.util.Timer$TimerImpl.run(Timer.java:284)
### Android 6 Permission Settings:

![screenshot_20151212-210739]
(https://cloud.githubusercontent.com/assets/5394395/11764968/c83155f0-a114-11e5-9857-2812961aabf6.png)

**Comment by ounsworth** [comment]
Brilliant, now if I turn off the Camera permission and then try to use the camera from the app, it makes a popup asking for the Camera permission. Good job, I'm closing this ticket.

![screenshot_20151226-134419](https://cloud.githubusercontent.com/assets/5394395/12007554/d6ba2d7c-abd7-11e5-9568-e6ecadff096f.png)
